import { CROPTOP, HOODIE, POLO, SWEATSHIRTS, TSHIRT } from "../assets";



export const products = [
  {
    id: 1,
    name: "Graphic Tee",
    image: POLO,
    description: "Trendy printed graphic tee for everyday wear",
    gsm: 180,
    color: "Black",
    size: ["S", "M", "L", "XL"],
    type: "polo",
    price: 699,
    discount: 10,
    categoryId: 1,
    collectionId: 1
  },
  {
    id: 2,
    name: "Oversized Hoodie",
    image: HOODIE,
    description: "Warm and stylish oversized hoodie",
    gsm: 300,
    color: "Gray",
    size: ["M", "L", "XL", "XXL"],
    type: "hoodie",
    price: 1199,
    discount: 15,
    categoryId: 2,
    collectionId: 2
  },
  {
    id: 3,
    name: "Printed Sweatshirt",
    image: TSHIRT,
    description: "Comfortable sweatshirt with trendy prints",
    gsm: 280,
    color: "White",
    size: ["S", "M", "L"],
    type: "sweatshirts",
    price: 999,
    discount: 12,
    categoryId: 3,
    collectionId: 3
  },
  {
    id: 4,
    name: "Casual Shirt",
    image: SWEATSHIRTS,
    description: "Casual everyday shirt with a soft touch",
    gsm: 160,
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    type: "croptop",
    price: 799,
    discount: 10,
    categoryId: 1,
    collectionId: 1
  },
  {
    id: 5,
    name: "Kids Dino Tee",
    image: CROPTOP,
    description: "Colorful dino print tee for kids",
    gsm: 140,
    color: "Green",
    size: ["XS", "S", "M"],
    type: "v-neck",
    price: 499,
    discount: 5,
    categoryId: 4,
    collectionId: 4
  },
  {
    id: 6,
    name: "Summer Tank",
    image: HOODIE,
    description: "Lightweight tank top for summer vibes",
    gsm: 130,
    color: "Yellow",
    size: ["S", "M", "L"],
    type: "t-shirt",
    price: 599,
    discount: 8,
    categoryId: 2,
    collectionId: 1
  },
  {
    id: 7,
    name: "Stylish Polo",
    image: HOODIE,
    description: "Smart casual polo shirt",
    gsm: 220,
    color: "Navy Blue",
    size: ["M", "L", "XL"],
    type: "polo",
    price: 899,
    discount: 10,
    categoryId: 1,
    collectionId: 2
  },
  {
    id: 8,
    name: "Women’s Floral Top",
    image: CROPTOP,
    description: "Floral printed top perfect for summer",
    gsm: 150,
    color: "Pink",
    size: ["S", "M", "L"],
    type: "hoodie",
    price: 649,
    discount: 10,
    categoryId: 3,
    collectionId: 3
  },
  {
    id: 9,
    name: "Boys Graphic Tee",
    image: SWEATSHIRTS,
    description: "Cool and comfy tee for boys",
    gsm: 160,
    color: "Red",
    size: ["XS", "S", "M"],
    type: "croptop",
    price: 499,
    discount: 5,
    categoryId: 4,
    collectionId: 5
  },
  {
    id: 10,
    name: "Zipped Hoodie",
    image: HOODIE,
    description: "Classic zipped hoodie for all seasons",
    gsm: 320,
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    type: "t-shirt",
    price: 1299,
    discount: 20,
    categoryId: 2,
    collectionId: 6
  },
  {
    id: 11,
    name: "Classic Crop Top",
    image: CROPTOP,
    description: "A flattering crop top perfect for summer wear.",
    gsm: "160 GSM",
    color: "Lilac",
    size: ["XS", "S", "M", "L"],
    type: "Crop Top",
    price: 499,
    discount: 10,
    categoryId: 3,
    collectionId: 2,
  },
  {
    id: 12,
    name: "Couples Set Black",
    image: CROPTOP,
    description: "Coordinated black t-shirts for couples.",
    gsm: "190 GSM",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    type: "Couples Wear",
    price: 1099,
    discount: 25,
    categoryId: 5,
    collectionId: 6,
  },
  {
    id: 13,
    name: "Cartoon Kids Tee",
    image: SWEATSHIRTS,
    description: "Bright and fun cartoon print for kids.",
    gsm: "150 GSM",
    color: "Orange",
    size: ["2Y", "4Y", "6Y"],
    type: "T-Shirt",
    price: 449,
    discount: 15,
    categoryId: 4,
    collectionId: 4,
  },
  {
    id: 14,
    name: "Long Sleeve Basics",
    image: HOODIE,
    description: "Versatile long sleeve t-shirt for all seasons.",
    gsm: "180 GSM",
    color: "Grey",
    size: ["S", "M", "L", "XL"],
    type: "T-Shirt",
    price: 549,
    discount: 10,
    categoryId: 1,
    collectionId: 1,
  },
  {
    id: 15,
    name: "Classic Hoodie",
    image: CROPTOP,
    description: "Comfortable hoodie for mild winter days.",
    gsm: "240 GSM",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    type: "Hoodie",
    price: 899,
    discount: 20,
    categoryId: 2,
    collectionId: 2,
  },
  {
    id: 16,
    name: "Slim Fit Tee",
    image: CROPTOP,
    description: "Chic and comfortable tee for women.",
    gsm: "170 GSM",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    type: "T-Shirt",
    price: 499,
    discount: 10,
    categoryId: 3,
    collectionId: 3,
  },
  {
    id: 17,
    name: "Sleeveless Polo",
    image: POLO,
    description: "Stylish sleeveless option for casual outings.",
    gsm: "160 GSM",
    color: "White",
    size: ["S", "M", "L"],
    type: "Polo",
    price: 549,
    discount: 15,
    categoryId: 1,
    collectionId: 1,
  },
  {
    id: 18,
    name: "Kids Polo Tee",
    image: HOODIE,
    description: "Sporty look for little champs.",
    gsm: "150 GSM",
    color: "Red",
    size: ["2Y", "4Y", "6Y"],
    type: "T-Shirt",
    price: 499,
    discount: 20,
    categoryId: 4,
    collectionId: 5,
  },
  {
    id: 19,
    name: "Street Hoodie",
    image: SWEATSHIRTS,
    description: "Urban style hoodie for daily comfort.",
    gsm: "250 GSM",
    color: "Olive",
    size: ["M", "L", "XL"],
    type: "Hoodie",
    price: 1099,
    discount: 25,
    categoryId: 2,
    collectionId: 6,
  },
  {
    id: 20,
    name: "Nightwear Tee",
    image: POLO,
    description: "Soft and breathable tee for a good night's sleep.",
    gsm: "140 GSM",
    color: "Blue",
    size: ["M", "L", "XL"],
    type: "T-Shirt",
    price: 399,
    discount: 10,
    categoryId: 3,
    collectionId: 3,
  }
];

  