import { CROPTOP, HOODIE, POLO, SWEATSHIRTS, TSHIRT } from "../assets";
export const viewproducts = [
  {
    id: 1,
    name: "Polo",
    image: POLO,
    description: "Comfortable black full-sleeve polo shirt",
    GSM: 220,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 699,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 1
  },
  {
    id: 2,
    name: "V-Neck",
    image: SWEATSHIRTS,
    description: "Stylish white V-neck t-shirt",
    GSM: 180,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 499,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 15,
    productId: 11
  },
  {
    id: 3,
    name: "T-shirt",
    image: TSHIRT,
    description: "Classic blue round neck t-shirt",
    GSM: 200,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 549,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 5,
    productId: 12
  },
  {
    id: 4,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Trendy grey Henley with buttons",
    GSM: 220,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 649,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 8,
    productId: 13
  },
  {
    id: 5,
    name: "hoodie",
    image: HOODIE,
    description: "Cool sleeveless gym t-shirt",
    GSM: 160,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 399,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 12,
    productId: 14
  },
  {
    id: 6,
    name: "Crop top",
    image: CROPTOP,
    description: "White tee with graphic print",
    GSM: 200,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 599,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 15
  },
  {
    id: 7,
    name: "Tank Top",
    image: SWEATSHIRTS,
    description: "Black cotton tank top",
    GSM: 170,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 299,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 7,
    productId: 16
  },
  {
    id: 8,
    name: "T-shirt",
    image: TSHIRT,
    description: "Blue and white striped tee",
    GSM: 190,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 579,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 9,
    productId: 17
  },
  {
    id: 9,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Red and white baseball sleeve t-shirt",
    GSM: 210,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 639,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 11,
    productId: 18
  },
  {
    id: 10,
    name: "Crop top",
    image: CROPTOP,
    description: "Navy blue pocket t-shirt",
    GSM: 180,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 519,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 6,
    productId: 19
  },
  {
    id: 11,
    name: "Hoodie",
    image: HOODIE,
    description: "Grey and black raglan tee",
    GSM: 200,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 559,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 20
  },
  {
    id: 12,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Trendy longline black t-shirt",
    GSM: 210,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 679,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 14,
    productId: 21
  },
  {
    id: 13,
    name: "Tank top",
    image: TSHIRT,
    description: "Military camo print t-shirt",
    GSM: 220,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 599,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 22
  },
  {
    id: 14,
    name: "Tank top",
    image: SWEATSHIRTS,
    description: "Colorful tie-dye print t-shirt",
    GSM: 200,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 629,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 13,
    productId: 23
  },
  {
    id: 15,
    name: "oversized",
    image: HOODIE,
    description: "Loose fit oversized t-shirt",
    GSM: 230,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 749,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 24
  },
  {
    id: 16,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Printed slogan tee",
    GSM: 200,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 599,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 12,
    productId: 25
  },
  {
    id: 17,
    name: "oversized",
    image: CROPTOP,
    description: "Grey tee with side zipper",
    GSM: 215,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 679,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 9,
    productId: 26
  },
  {
    id: 18,
    name: "V-neck",
    image: TSHIRT,
    description: "Retro style orange and brown tee",
    GSM: 190,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 559,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 11,
    productId: 27
  },
  {
    id: 19,
    name: "Hoodie",
    image: HOODIE,
    description: "Fashionable cropped t-shirt",
    GSM: 170,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 489,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 28
  },
  {
    id: 20,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Performance fit sports tee",
    GSM: 210,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 699,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 29
  },
  {
    id: 21,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Textured cotton slub t-shirt",
    GSM: 195,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 539,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 8,
    productId: 30
  },
  {
    id: 22,
    name: "Hoodie",
    image: HOODIE,
    description: "Two-tone fabric t-shirt",
    GSM: 205,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 589,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 9,
    productId: 1
  },
  {
    id: 23,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Smart casual collared tee",
    GSM: 215,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 669,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 11,
    productId: 2
  },
  {
    id: 24,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Breathable mesh fabric tee",
    GSM: 180,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 499,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 12,
    productId: 3
  },
  {
    id: 25,
    name: "T-shirt",
    image: TSHIRT,
    description: "Stylish color-block pattern tee",
    GSM: 200,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 619,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 13,
    productId: 4
  },
  {
    id: 26,
    name: "Crop top",
    image: CROPTOP,
    description: "Printed pattern polo t-shirt",
    GSM: 220,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 719,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 5
  },
  {
    id: 27,
    name: "Crop top",
    image: CROPTOP,
    description: "Wide scoop neck t-shirt",
    GSM: 190,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 539,
    type:["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 9,
    productId: 6
  },
  {
    id: 28,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Solid monochrome color tee",
    GSM: 200,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 609,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 7
  },
  {
    id: 29,
    name: "T-shirt",
    image: TSHIRT,
    description: "Tee with contrast color sleeves",
    GSM: 200,
    color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 619,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 10,
    productId: 8
  },
  {
    id: 30,
    name: "Sweatshirts",
    image: SWEATSHIRTS,
    description: "Warm fleece-lined t-shirt",
    GSM: 240,
   color: ["white","Black","Grey","navy blue","red" ,"blue", "green","yellow"],
    size: ["XS","S", "M", "L", "XL","XXL","3XL"],
    total: 799,
    type: ["full sleeve","sleeveless","crop full sleeve","crop sleeveless"],
    discount: 15,
    productId: 9
  }
];

